name: Upload and Process Only New Files on Azure VM

on:
  push:
    branches:
      - main
    paths:
      - 'test/**'  # Monitor changes in this folder

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Newly Added Files
        id: new_files
        run: |
          git fetch origin main
          NEW_FILES=$(git diff --name-only HEAD^ HEAD | grep '^your-folder/')
          echo "NEW_FILES=$NEW_FILES" >> $GITHUB_ENV

      - name: Print New Files
        run: echo "New files to upload: ${{ env.NEW_FILES }}"

      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client sshpass

      - name: Upload Only New Files to Azure VM
        run: |
          if [ -n "${{ env.NEW_FILES }}" ]; then
            for file in ${{ env.NEW_FILES }}; do
              sshpass -p "${{ secrets.AZURE_VM_PASSWORD }}" scp -o StrictHostKeyChecking=no "$file" "${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_IP }}:/home/${{ secrets.AZURE_VM_USERNAME }}/uploads/"
            done
          else
            echo "No new files to upload."
          fi

      - name: Run Python Processing Script on Azure VM
        if: env.NEW_FILES != ''
        run: |
          sshpass -p "${{ secrets.AZURE_VM_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_IP }} "python3 /home/${{ secrets.AZURE_VM_USERNAME }}/process_file.py"
